{{- if .Values.agent.plugins.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.agent.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.agent.plugins.config_files | indent 2 }}
{{- end}}
