{{- if and (.Values.rbac.create) (not .Values.agent.serviceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "agent.fullname" . }}"
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.agent.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}
