{{- if and (.Values.rbac.create) (not .Values.agent.serviceAccount) }}
kind: ClusterRoleBinding
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1alpha1" }}
apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- end }}
metadata:
  name: "{{ template "agent.fullname" . }}"
subjects:
  - kind: ServiceAccount
    name: "{{ template "agent.fullname" . }}"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: "{{ template "agent.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
