{{- if .Values.alarms.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "alarms.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.alarms.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.alarms.definitions_configuration | indent 2 }}
{{- end }}
