apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.api.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "api.fullname" . }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - name: http
    port: {{ .Values.api.service.port}}
    {{- if .Values.api.service.node_port }}
    nodePort: {{ .Values.api.service.node_port }}
    {{- end }}
  selector:
    app: {{ template "fullname" . }}
    component: "{{ .Values.api.name }}"
