{{- if and (.Values.rbac.create) (not .Values.cleanup.serviceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cleanup.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.cleanup.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}
