{{- if .Values.forwarder.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forwarder.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.forwarder.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.forwarder.metric_configuration | indent 2 }}
{{- end }}
