{{- if .Values.keystone.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.keystone.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "keystone.fullname" . }}
data:
  preload.yml: |
    users:
      - username: mini-mon
        password: {{ .Values.keystone.users.mini_mon.password }}
        project: mini-mon
        role: monasca-user

      - username: monasca-agent
        password: {{ .Values.keystone.users.monasca_agent.password }}
        project: mini-mon
        role: monasca-agent

      - username: mini-mon
        password: {{ .Values.keystone.users.mini_mon.password }}
        project: mini-mon
        role: admin

      - username: admin
        password: {{ .Values.keystone.users.admin.password }}
        project: admin
        role: monasca-user

      - username: demo
        password: {{ .Values.keystone.users.demo.password }}
        project: demo
        role: monasca-user

      - username: monasca-read-only-user
        password: {{ .Values.keystone.users.monasca_read_only.password }}
        project: mini-mon
        role: monasca-read-only-user

    endpoints:
      - name: monasca
        description: Monasca monitoring service
        type: monitoring
        region: RegionOne
        interfaces:
          - name: internal
            url: http://{{ template "api.fullname" . }}:{{ .Values.api.service.port }}/v2.0
          - name: public
            url: http://{{ template "api.fullname" . }}:{{ .Values.api.service.port }}/v2.0
            {{- if .Values.api.service.node_port }}
            resolve: true
            {{- end }}
          - name: admin
            url: http://{{ template "api.fullname" . }}:{{ .Values.api.service.port }}/v2.0
            {{- if .Values.api.service.node_port }}
            resolve: true
            {{- end }}
{{- end}}
