{{- if .Values.grafana.enabled }}
{{- if .Values.grafana.local_mysql_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-mysql-grafana-secret"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  username: {{ b64enc .Values.mysql.users.grafana.username | quote }}
  password: {{ b64enc .Values.mysql.users.grafana.password | quote }}
{{- end}}
{{- end}}
